# Generated by Django 5.2.1 on 2025-10-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='portfolio_template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', help_text='Select the default portfolio template style', max_length=20),
        ),
    ]
