# Generated by Django 5.2.1 on 2025-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0004_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='fabric_weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='target_market',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
