# Generated by Django 5.2.1 on 2025-11-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_portfolio', '0005_design_additional_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_notes',
            field=models.TextField(blank=True, help_text='Internal notes for review before publishing'),
        ),
        migrations.CreateModel(
            name='DesignerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_conversations_as_a', to=settings.AUTH_USER_MODEL)),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_conversations_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='designer_portfolio.designerconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='designerconversation',
            constraint=models.CheckConstraint(condition=models.Q(('participant_a', models.F('participant_b')), _negated=True), name='designer_conversation_participants_distinct'),
        ),
        migrations.AddConstraint(
            model_name='designerconversation',
            constraint=models.UniqueConstraint(fields=('participant_a', 'participant_b'), name='designer_conversation_unique_pair'),
        ),
    ]
