# Generated by Django 5.2.1 on 2025-10-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redym_portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('6months', '6 Months'), ('yearly', 'Yearly')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.IntegerField()),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paypal_plan_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='design',
            name='color_palette',
            field=models.CharField(blank=True, help_text='Color codes and descriptions', max_length=500),
        ),
        migrations.AddField(
            model_name='design',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='fabric_details',
            field=models.TextField(blank=True, help_text='Fabric specifications and requirements'),
        ),
        migrations.AddField(
            model_name='design',
            name='production_notes',
            field=models.TextField(blank=True, help_text='Special production requirements or notes'),
        ),
        migrations.AddField(
            model_name='design',
            name='size_range',
            field=models.CharField(blank=True, help_text='Available size range (e.g., XS-XL)', max_length=100),
        ),
        migrations.AddField(
            model_name='design',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target retail price', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='techpack_excel',
            field=models.FileField(blank=True, help_text='Upload tech pack as Excel file', null=True, upload_to='designs/techpacks/excel/'),
        ),
        migrations.AddField(
            model_name='design',
            name='techpack_pdf',
            field=models.FileField(blank=True, help_text='Upload tech pack as PDF file', null=True, upload_to='designs/techpacks/pdf/'),
        ),
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself and your design philosophy', max_length=1000)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='designers/profiles/')),
                ('portfolio_website', models.URLField(blank=True, help_text='Your personal website or portfolio')),
                ('instagram_handle', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100)),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of design experience')),
                ('specialization', models.CharField(blank=True, help_text='e.g., Sustainable Fashion, Avant-garde, Streetwear', max_length=200)),
                ('education', models.CharField(blank=True, help_text='Educational background', max_length=300)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('available_for_collaborations', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Public contact email (optional)', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designer Profile',
                'verbose_name_plural': 'Designer Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('free_trial', 'Free Trial'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='free_trial', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('paypal', 'PayPal'), ('applepay', 'Apple Pay')], max_length=20, null=True)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('trial_end_date', models.DateTimeField()),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redym_portfolio.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('paypal', 'PayPal'), ('applepay', 'Apple Pay')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='redym_portfolio.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
