# Generated by Django 5.2.1 on 2025-10-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redym_portfolio', '0002_subscriptionplan_alter_design_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='available_for_collaborations',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='portfolio_website',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='auto_renewal',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='paypal_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription_start_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_start_date',
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Credit Card'), ('paypal', 'PayPal'), ('applepay', 'Apple Pay')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redym_portfolio.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('free_trial', 'Free Trial'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='free_trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
