# Generated by Django 5.2.1 on 2025-10-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redym_portfolio', '0003_alter_designerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designerprofile',
            options={'verbose_name': 'Designer Profile', 'verbose_name_plural': 'Designer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='designerprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='available_for_collaborations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public contact email (optional)', max_length=254),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='education',
            field=models.CharField(blank=True, help_text='Educational background', max_length=300),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='portfolio_website',
            field=models.URLField(blank=True, help_text='Your personal website or portfolio'),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='designers/profiles/'),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g., Sustainable Fashion, Avant-garde, Streetwear', max_length=200),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of design experience'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(default='Standard Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renewal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Tell us about yourself and your design philosophy', max_length=1000),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('6months', '6 Months'), ('yearly', 'Yearly')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('paypal', 'PayPal'), ('applepay', 'Apple Pay')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redym_portfolio.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('past_due', 'Past Due')], default='free_trial', max_length=20),
        ),
    ]
